version: "3"

services:
  home-vue:
    image: ghcr.io/mrsessions/home-vue:latest
    build:
      context: ./
    container_name: home-vue
    environment:
      - POCKETBASE_DISABLE_UI=false # Set to true to disable the PocketBase UI
    ports:
      - 8090:8090
    volumes:
      - home-vue:/app/pb_data
    restart: unless-stopped

volumes:
  home-vue: